approvedGitRepositories:
  - "**"

enableScripts: true

httpTimeout: 600000

nodeLinker: node-modules

npmMinimalAgeGate: 7d

npmPreapprovedPackages:
  - "@elliottech/*"
  - zklighter-perps
  - zklighter-perps-exp

npmScopes:
  elliottech:
    npmAuthToken: "${NPM_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-pkg-guard.cjs
